### ISSUE TITLE
django-ckeditor assets not found(404) on server

### ISSUE THREAD

**Issue by travishen** [COAStatistics/aprp#45]
**behavior**
1. It should look for /static/ckeditor/ckeditor/config.js etc. but looked for wrong location:
```
GET http://host/config.js?t=H8DA net::ERR_ABORTED 404 (Not Found)
GET http://host/lang/zh.js?t=H8DA net::ERR_ABORTED 404 (Not Found)
GET http://host/skins/moono-lisa/editor.css?t=H8DA net::ERR_ABORTED 404 (Not Found)
```
2. ckeditor assets worked in admin page

**settings**
STATIC_ROOT = os.path.join(BASE_DIR, "live-static-files", "static-root")
STATICFILES_STORAGE = 'whitenoise.django.GzipManifestStaticFilesStorage'

CKEDITOR_BASEPATH = "/static/ckeditor/ckeditor"

**Comment by MatsuiLin101** [comment]
When CKEditor uses outside of Django admin page, ckeditor-init.js and ckeditor.js files must be loaded according to Django-ckeditor documentation.

But the use of documentation has some issue cause Django-ckeditor cannot use outside of Django-admin page, because of config.js has the wrong URL.

Modify the method of load script to:
<script src="{% static 'ckeditor/ckeditor-init.js' %}" data-ckeditor-basepath="/static/ckeditor/ckeditor/" id="ckeditor-init-script"></script>
Then ckeditor works fine.
